### ISSUE TITLE
hello, i cannot install the latest version.

### ISSUE THREAD

**Issue by ericvlog** [Sam-Max/plugin.video.jacktook#14]
I can open setting but when i open addons inside its error, below are log.

2024-02-26 19:04:14.826 T:66124    info <general>: CActiveAESink::OpenSink - initialize sink
2024-02-26 19:04:27.036 T:72564   error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-02-26 19:04:28.903 T:72860   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: unsupported operand type(s) for |: 'type' and 'type'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.jacktook\jacktook.py", line 3, in <module>
                                                       from resources.lib.navigation import run
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.jacktook\resources\lib\navigation.py", line 4, in <module>
                                                       from resources.lib.api.premiumize_api import Premiumize
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.jacktook\resources\lib\api\premiumize_api.py", line 16, in <module>
                                                       class DebridClient:
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.jacktook\resources\lib\api\premiumize_api.py", line 85, in DebridClient
                                                       target_status: str | int,
                                                   TypeError: unsupported operand type(s) for |: 'type' and 'type'
                                                   -->End of Python script error report<--
                                                   
2024-02-26 19:04:29.790 T:74700   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/
2024-02-26 19:04:31.904 T:72564   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/) failed

**Comment by Sam-Max** [comment]
fixed on latest version 0.1.8

**Comment by ericvlog** [comment]
I Setting all and hide uncache , but when i play got error.

2024-02-26 23:42:25.610 T:10584   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/settings
2024-02-26 23:42:35.986 T:79692   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/settings) failed
2024-02-26 23:42:48.409 T:1644     info <general>: [JACKTOOK] http://192.168.1.100:9117/api/v2.0/indexers/all/results/torznab/api?apikey=XXXXXXXXXXXXXX-I-HIDDING&q=The Marvels
2024-02-26 23:42:59.542 T:81032 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:3168, P:52472, O:61392.
2024-02-26 23:43:15.533 T:81720   error <general>: [plugin.video.torrest] [bittorrent] [thread-74988] operation=add_torrent_data, message='Failed adding torrent data: expected value (list, dict, int or string) in bencoded string'
2024-02-26 23:43:15.538 T:81720   error <general>: [plugin.video.torrest] [api] [thread-74988] operation=intercept, method=POST, address=127.0.0.1, uri=/add/torrent?ignore_duplicate=true&download=false, elapsedTime=7, statusCode=500
2024-02-26 23:43:15.550 T:79692   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.jacktook/play_torrent?query=https%3A%2F%2Ftherarbg.to%2Fpost-detail%2F6858f1%2Fthe-marvels-2023-1080p-webrip-aac5-1-yts-mx%2F++609681+The+Marvels+2023+1080p+WEBRip+AAC5+1+YTS+MX]
2024-02-26 23:43:15.551 T:77800   error <general>: [plugin.video.torrest] Caught exception:
                                                   Traceback (most recent call last):
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 447, in run
                                                       plugin.run()
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 53, in wrapper
                                                       raise e
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 44, in wrapper
                                                       func(*args, **kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 98, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 282, in play_url
                                                       info_hash = api.add_torrent_obj(r.raw, ignore_duplicate=True)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\torrest\api.py", line 99, in add_torrent_obj
                                                       r = self._post("/add/torrent", files={"torrent": obj}, params={
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\torrest\api.py", line 182, in _post
                                                       return self._request("post", url, **kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\torrest\api.py", line 197, in _request
                                                       raise TorrestError(error)
                                                   lib.torrest.api.TorrestError: expected value (list, dict, int or string) in bencoded string
2024-02-26 23:43:29.571 T:81720   error <general>: [plugin.video.torrest] [bittorrent] [thread-1644] operation=add_torrent_data, message='Failed adding torrent data: expected value (list, dict, int or string) in bencoded string'
2024-02-26 23:43:29.575 T:81720   error <general>: [plugin.video.torrest] [api] [thread-1644] operation=intercept, method=POST, address=127.0.0.1, uri=/add/torrent?ignore_duplicate=true&download=false, elapsedTime=0, statusCode=500
2024-02-26 23:43:29.580 T:79692   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.jacktook/play_torrent?query=https%3A%2F%2Fwww.limetorrents.lol%2FThe-Marvels-%282023%29-%5B1080p%5D-%5BWEBRip%5D-%5B5-1%5D-torrent-18346386.html++609681+The+Marvels+%282023%29+%5B1080p%5D+%5BWEBRip%5D+%5B5+1%5D]
2024-02-26 23:43:29.583 T:69380   error <general>: [plugin.video.torrest] Caught exception:
                                                   Traceback (most recent call last):
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 447, in run
                                                       plugin.run()
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 53, in wrapper
                                                       raise e
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 44, in wrapper
                                                       func(*args, **kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 98, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 282, in play_url
                                                       info_hash = api.add_torrent_obj(r.raw, ignore_duplicate=True)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\torrest\api.py", line 99, in add_torrent_obj
                                                       r = self._post("/add/torrent", files={"torrent": obj}, params={
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\torrest\api.py", line 182, in _post
                                                       return self._request("post", url, **kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\torrest\api.py", line 197, in _request
                                                       raise TorrestError(error)
                                                   lib.torrest.api.TorrestError: expected value (list, dict, int or string) in bencoded string
2024-02-26 23:43:38.517 T:81032 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:45288, P:32976, O:40184.
2024-02-26 23:44:15.667 T:81032 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:16416, P:4352, O:13560.

**Comment by Sam-Max** [comment]
@ericvlog which indexer are you using to play with Torrest?

**Comment by ericvlog** [comment]
BitSearch Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
LimeTorrents Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
MegaPeer Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
NoNaMe Club Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
Nyaa.si Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
RuTor Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
RuTracker Semi-Private | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
RuTracker.RU Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
Solid Torrents Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
The Pirate Bay Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
TheRARBG Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
Torrent9 Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
UnionDHT Public | Copy RSS Feed Copy Torznab Feed Copy Potato Feed    Test
YTS Public

When I play movies with that cache link error. Below is log.

2024-02-29 15:24:23.503 T:77380    info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2024-02-29 15:24:44.874 T:87508    info <general>: [JACKTOOK] http://192.168.1.100:9117/api/v2.0/indexers/all/results/torznab/api?apikey=tpk4t3g1d0fbosfj5p08lz5kahfcbc6p&q=Poor Things
2024-02-29 15:25:02.714 T:64380   error <general>: [plugin.video.torrest] [bittorrent] [thread-74804] operation=add_torrent_data, message='Failed adding torrent data: expected value (list, dict, int or string) in bencoded string'
2024-02-29 15:25:02.718 T:64380   error <general>: [plugin.video.torrest] [api] [thread-74804] operation=intercept, method=POST, address=127.0.0.1, uri=/add/torrent?ignore_duplicate=true&download=false, elapsedTime=1, statusCode=500
2024-02-29 15:25:02.732 T:77380   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.jacktook/play_torrent?query=https%3A%2F%2Fwww.limetorrents.lol%2FPoor-Things-2023-2160p-WEB-DL-DDP5-1-Atmos-DV-HDR-H-265-FLUX%5BTGx%5D-torrent-18390247.html++792307+Poor+Things+2023+2160p+WEB+DL+DDP5+1+Atmos+DV+HDR+H+265+FLUX%5BTGx%5D]
2024-02-29 15:25:02.762 T:88180   error <general>: [plugin.video.torrest] Caught exception:
                                                   Traceback (most recent call last):
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 447, in run
                                                       plugin.run()
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 53, in wrapper
                                                       raise e
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 44, in wrapper
                                                       func(*args, **kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 98, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\navigation.py", line 282, in play_url
                                                       info_hash = api.add_torrent_obj(r.raw, ignore_duplicate=True)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\torrest\api.py", line 99, in add_torrent_obj
                                                       r = self._post("/add/torrent", files={"torrent": obj}, params={
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\torrest\api.py", line 182, in _post
                                                       return self._request("post", url, **kwargs)
                                                     File "C:\Users\plsharevme\AppData\Roaming\Kodi\addons\plugin.video.torrest\lib\torrest\api.py", line 197, in _request
                                                       raise TorrestError(error)
                                                   lib.torrest.api.TorrestError: expected value (list, dict, int or string) in bencoded string
2024-02-29 15:28:15.910 T:84608    info <general>: ###OnNotificationActions###: PAUSING Fen Light Services Due to Device Sleep
2024-02-29 15:28:15.916 T:88692    info <general>: ###OnNotificationActions###: PAUSING Fen Services Due to Device Sleep

**Comment by asylumexp** [comment]
do you have a torrest instance setup? and is the IP in the settings?
