### ISSUE TITLE
Addon not launching Kodi Omega.

### ISSUE THREAD

**Issue by Anon1337Elite** [Sam-Max/plugin.video.jacktook#50]
2024-07-05 20:32:27.537 T:14896   error <general>: EXCEPTION: Unknown addon id 'plugin.video.jacktorr'.
2024-07-05 20:32:27.547 T:5964     info <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2024-07-05 20:32:27.582 T:14896   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'type' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Kodi\portable_data\addons\plugin.video.jacktook\jacktook.py", line 3, in <module>
                                                       from lib.navigation import run
                                                     File "C:\Kodi\portable_data\addons\plugin.video.jacktook\lib\navigation.py", line 14, in <module>
                                                       from lib.clients.search import search_client
                                                     File "C:\Kodi\portable_data\addons\plugin.video.jacktook\lib\clients\search.py", line 1, in <module>
                                                       from lib.clients.utils import get_client
                                                     File "C:\Kodi\portable_data\addons\plugin.video.jacktook\lib\clients\utils.py", line 7, in <module>
                                                       from lib.clients.zilean import Zilean
                                                     File "C:\Kodi\portable_data\addons\plugin.video.jacktook\lib\clients\zilean.py", line 13, in <module>
                                                       class Zilean:
                                                     File "C:\Kodi\portable_data\addons\plugin.video.jacktook\lib\clients\zilean.py", line 62, in Zilean
                                                       def api_scrape(self, query) -> tuple[Dict[str, str], int]:
                                                   TypeError: 'type' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2024-07-05 20:32:27.639 T:8948    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.jacktook/
2024-07-05 20:32:27.643 T:18860   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jacktook/) failed
2024-07-05 20:32:29.851 T:18204    info <general>: JSONRPC Server: New connection added
2024-07-05 20:32:29.853 T:18204    info <general>: JSONRPC Server: Disconnection detected
2024-07-05 20:32:29.854 T:18204    info <general>: JSONRPC Server: New connection added
2024-07-05 20:32:29.856 T:18204    info <general>: JSONRPC Server: Disconnection detected

Cant make it work at all

**Comment by Sam-Max** [comment]
Oh yes, it is an issue with the python version your kodi environment is using.

**Comment by Sam-Max** [comment]
I pushed an update, download this repo as a zip file and install it, and test if it works now.

**Comment by Anon1337Elite** [comment]
> I pushed an update, download this repo as a zip file and install it, and test if it works now.

thank u it works. im having an issue with jaktor as well i post it in its own git
