### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '2.12 GB'

### ISSUE THREAD

**Issue by saucepanlid** [Sam-Max/plugin.video.jacktook#51]
Hi there,

Loving the extension. I can clearly see inspiration from Elementum but with many changes under the hood to bring it up to date and to leverage other software to do the heavy lifting.

When using Jacket or Prowlarr, I get the following errors: 

This is with Jactook 0.3.0

```
2024-07-26 12:07:12.822 T:19364   error <general>: ERROR:root:Caught exception:
                                                   Traceback (most recent call last):
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\navigation.py", line 1190, in run
                                                       plugin.run()
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\navigation.py", line 144, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\navigation.py", line 144, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\navigation.py", line 144, in wrapper
                                                       return func(*args, **kwargs)
                                                     [Previous line repeated 4 more times]
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\navigation.py", line 454, in search
                                                       show_indexers_results(
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\plugin.video.jacktook\lib\indexer.py", line 59, in show_indexers_results
                                                       bytes_to_human_readable(int(res.get("size", 0)))
                                                   ValueError: invalid literal for int() with base 10: '2.12 GB'
```

Upon some investigation, it seems to be because cached results from Burst were reused when changing indexers, so it maybe nescessary to invalidate the cache when switching indexers.

**Comment by Sam-Max** [comment]
I created a menu item called "Rescrape Item" to make a new request and avoid previous cached results, but it is also a good idea to add a logic to invalidate cache when user changes indexers.
