### ISSUE TITLE
Real-Debrid authentication error

### ISSUE THREAD

**Issue by Xupack88** [Sam-Max/plugin.video.jacktook#66]
Kubuntu 24.04
Kodi 21.1
Jacktook 0.3.4

When I try to authorize Real-Debrid I get the following error:

2024-11-24 21:42:59.696 T:222      info <general>: [###JACKTOOKLOG###] Traceback (most recent call last):
                                                     File "/home/xupack/.var/app/tv.kodi.Kodi/data/addons/plugin.video.jacktook/lib/api/debrid/debrid_client.py", line 45, in _handle_errors
                                                       response.raise_for_status()
                                                     File "/home/xupack/.var/app/tv.kodi.Kodi/data/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.real-debrid.com/oauth/v2/device/credentials?client_id=REDACTED&code=REDACTED
                                                   
2024-11-24 21:42:59.697 T:222      info <general>: [###JACKTOOKLOG###] {'error': None, 'error_code': None}
2024-11-24 21:42:59.697 T:222      info <general>: [###JACKTOOKLOG###] 403

![RD](https://github.com/user-attachments/assets/f11cba0a-07fb-4d95-8d5a-a93a328c9881)

**Comment by Sam-Max** [comment]
It is fixed now on v0.3.5
