### ISSUE TITLE
Addon won't open in Windows

### ISSUE THREAD

**Issue by latinokodi** [Sam-Max/plugin.video.jacktook#70]
Hi, sorry to bother, in latest version 0.3.9 when opening addon in windows we get JACKTOOK ERROR and addon wont start. Same issue we had a couple of versions back, you solved it leaving default python version to the one included in KODI but I don't know if it is caused by the same issue. Here is the log:

```
2024-12-06 20:50:54.964 T:21124   error <general>: EXCEPTION: Unknown addon id 'plugin.video.jacktorr'.
2024-12-06 20:50:55.103 T:21124   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'type' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "D:\LKOmega21.1Tests\portable_data\addons\plugin.video.jacktook\jacktook.py", line 3, in <module>
                                                       from lib.navigation import run
                                                     File "D:\LKOmega21.1Tests\portable_data\addons\plugin.video.jacktook\lib\navigation.py", line 16, in <module>
                                                       from lib.utils.ed_utils import get_ed_pack_info, show_ed_pack_info
                                                     File "D:\LKOmega21.1Tests\portable_data\addons\plugin.video.jacktook\lib\utils\ed_utils.py", line 3, in <module>
                                                       from lib.clients.debrid.easydebrid import EasyDebrid
                                                     File "D:\LKOmega21.1Tests\portable_data\addons\plugin.video.jacktook\lib\clients\debrid\easydebrid.py", line 4, in <module>
                                                       class EasyDebrid(DebridClient):
                                                     File "D:\LKOmega21.1Tests\portable_data\addons\plugin.video.jacktook\lib\clients\debrid\easydebrid.py", line 48, in EasyDebrid
                                                       def get_torrent_instant_availability(self, urls: list[str]):
                                                   TypeError: 'type' object is not subscriptable

```

**Comment by Sam-Max** [comment]
I will fix soon, it is the same thing again, sorry
